# render.yaml
# Render.com deployment configuration for CI/CD

services:
  - type: web
    name: jobtracker
    env: docker
    plan: free
    autoDeploy: true
    buildCommand: docker compose build     # How to build the container
    startCommand: docker compose up        # How to start it
    envVars:
      - key: FLASK_SECRET_KEY
        sync: false
      - key: GOOGLE_OAUTH_CLIENT_ID
        sync: false
      - key: GOOGLE_OAUTH_CLIENT_SECRET
        sync: false
